### ISSUE TITLE
When searching chinese characters result is entry with description that consists of text with characters searched located randomly in text

### ISSUE THREAD

**Issue by Rkrushanovskij** [ipfs-search/ipfs-search#103]
Hi!
When i\`m trying to find chinese text, i`m getting results that consists of not exactly matched text.
For example:
Searching "自动提取代码库标签":
One of the results with description (take a look to bold characters - it is what i searched):
SqlMapConfig.xml文件使用连接池的方式解决了数据**库**连接创建和释放频繁所造成的性能影响。 2. 大量的sql存在于**代码**之中，造成**代码**的可维护性低。mybatis只用xml文件对sql进行统一管理，方便维护。 3. jdbc操作中存在参数时，需要准确的定位参数的位置和对应占位符的个数，否则会出错。mybatis通过**提**供参数对象的方式解决了该问题。 4. sql语句在编写时，如果存在**动**态条件则不容易处理。mybatis**提**供**动**态sql编写机制，时用户可以根据**自**己传入参数的情况进行sql语句的**动**态编写

Does here any way to find exactly combination of characters?
Thanks!

**Comment by dokterbob** [comment]
I'm not sure. We're using Elasticsearch. The query is made in this file:
https://github.com/ipfs-search/ipfs-search-api/blob/master/search.js

As you see, we're taking the query literally from the input. But perhaps there are UTF-8 issues, or perhaps Elasticsearch has difficulties with Chinese. You might run the crawler on your own machine using Docker, then index a few Chinese files and play around with it. You might also look into any issues involving Elastcsearch and Chinese characters.

**Comment by Rkrushanovskij** [comment]
@dokterbob 
Are you using any analyzer plugin (see https://www.sitepoint.com/efficient-chinese-search-elasticsearch/) for chinese?

**Comment by dokterbob** [comment]
We’re not using any analyser for any languages at the moment. We’d love to but we’d need help integrating it into our infrastructure. We currently have all languages in the same index.

**Comment by Rkrushanovskij** [comment]
Got it, thanks!
