### ISSUE TITLE
Is it possible to search by search request AND last-seen parameter?

### ISSUE THREAD

**Issue by Rkrushanovskij** [ipfs-search/ipfs-search#105]
Hello!
Is there any way to search something with filtering by 'last-seen' field?
In the API it is the same query parameter (`q`) - how can i do it?
`/v1/search?q=something`
`/v1/search?q=last-seen:>now-1M`
Also, am i have ability to search for last week, for example? I tried `q=last-seen:>now-1W` and `q=last-seen:>now-7D` but it caused error 504.

**Comment by dokterbob** [comment]
It just works. 

Note that it should be `1w` not `1W`. Example: https://api.ipfs-search.com/v1/search?q=banana%20last-seen:%3Enow-1w
