### ISSUE TITLE
Feature: File Thumbnails

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs-search/ipfs-search#114]
For Image and Video file searching, there should be thumbnails.
> We should receive the thumbnails from the API. Ideally hosted over IPFS

**Comment by DonaldTsang** [comment]
A pretty smart idea: https://github.com/FLIF-hub/FLIF or https://github.com/cloudinary/fuif for progressively rendered thumbnail, such that it can take only the first N kilobytes of data to have an image resolution of 256px without the need of the other pieces of data.

**Comment by DonaldTsang** [comment]
https://github.com/ipfs-search/ipfs-search-frontend/issues/46

**Comment by dokterbob** [comment]
We're soon launching https://github.com/ipfs-search/nyats

See https://github.com/ipfs-search/dweb-search-frontend/pull/23/
