### ISSUE TITLE
About 50% of the files are not downloadable and no option to exclude them from search results

### ISSUE THREAD

**Issue by bitcoinmeetups** [ipfs-search/ipfs-search#121]
About 50% of the files are not downloadable and no option to exclude them from search results

Hi,

I'm BM, a very nice and polite guy.

I have been testing IPFS-SEARCH a few times but the results are a little bit so-so. In about 50% of the cases the files are not downloadable.

Also there is no option to exclude files that don't exist.

Please add an option to only include available files.

BM

**Comment by dokterbob** [comment]
Hi nice and polite guy,

Thanks for your very valid feedback. I'm afraid this problem has more to do with IPFS than with our infrastructure - it simply seems the case that IPFS has a hard time finding stuff. They are aware of it, and with IPFS 0.5 they have released a new DHT which (in time) should improve stuff.

On the other hand, we are already prioritising results which are 'recently seen' (and thus more likely to be available) by our sniffer. The next step is to actually store the amount of providers for hashes, similar to seeders in torrent searchers. However, this is pending a refactor of our entire datastructure and backend.

Lastly, we might try to fetch/precache resources the moment the search page is returned, this will allow files to start loading faster and would also allow us to give an indication on availability.

If you'd like to get involved with crunching of code, you are more than welcome to help out. Or perhaps you know someone who might. Golang and Elasticsearch are our tools of trade.

Thanks!
Mathijs

**Comment by dokterbob** [comment]
@madnificent What do you think about precaching search results and/or using timeouts in that process to tell users something about the actual availability of resources?
