### ISSUE TITLE
handleAddProvider logging for ipfs 0.5+ support

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search#122]
In particular, it seems that the `handleAddProvider` log message is not in the ipfs log tail stream anymore.

That message probably comes from https://github.com/libp2p/go-libp2p-kad-dht/blob/0d1a917f1a3ce5ad85ad19769314b120eb54639c/handlers.go#L339

We might need to create a plugin.

**Comment by dokterbob** [comment]
This seems to be the relevant changeset.

https://github.com/libp2p/go-libp2p-kad-dht/commit/445472b1f0f8c7b20a94072437f794a2ef7fc6f5#diff-31a4a7824225629df071a1cba8b785d5R341

**Comment by dokterbob** [comment]
It seems the message is an unstructured debug message `adding provider` which gets thrown to stderr of `ipfs daemon` when `ipfs log level dht debug` is set.

**Comment by dokterbob** [comment]
More hints... https://github.com/ipfs/go-ipfs/blob/master/plugin/plugins/peerlog/peerlog.go

**Comment by dokterbob** [comment]
https://github.com/ipfs/go-ipfs/issues/7065

**Comment by dokterbob** [comment]
Discussion from Matrix:

@Stebalien:
> at the moment, the simplest approach would be to run IPFS with IPFS_LOGGING_FMT=json to emit json events, turn on debug logging for the dht (ipfs log level dht debug), and listen to the daemon's stderr. Note: that'll produce a lot of noisy output.
The "cleanest" approach would be to write a custom datastore wrapper and inject it into go-ipfs through a datastore plugin (take a look at how the other datastores are implemented in, e.g., plugin/plugins/flatfs). Alternatively, you could run a custom dht-only node like https://github.com/ipfs/dht-node/blob/master/main.go (with the same datastore plugin).
The datastore wrapper would need to intercept datastore queries for keys starting with /providers/base32(CID).

**Comment by Stebalien** [comment]
The datastore route is basically:

1. Implement a datastore plugin like https://github.com/ipfs/go-ipfs/blob/31ca7ce24458b292469d0d4c85b23a420bd18acc/plugin/plugins/flatfs/flatfs.go#L1.
2. Implement a datastore like https://github.com/ipfs/go-ds-measure/blob/master/measure.go that wraps an underlying datastore, recording specific operations.
3. Record the keys from `Get` and `Put` calls for keys that start with `/providers/` and record the prefixes for `Query` calls that specify a `Query.Prefix` starting with `/providers/`.
4. These keys will be in the format `/providers/base32(cid_or_multihash)` and/or `/providers/base32(cid_or_multihash)/base32(provider_of_content)`.

Here's an example of using a datastore proxy to do pretty much the same thing: https://github.com/libp2p/hydra-booster/blob/master/datastore/proxy.go. In this case, we're listening for provider queries to help replicate provider records.

**Comment by dokterbob** [comment]
Reference: https://github.com/libp2p/go-libp2p-kad-dht/blob/08ab423f2fc5f3c3e3e9452fc2358dbc0610d369/providers/providers_manager.go#L22-L24

**Comment by dokterbob** [comment]
WIP
```
$ IPFS_LOGGING_FMT="json" ipfs daemon 2>/tmp/ipfs_log
$ ipfs log level dht debug
$ tail -f ipfs_log | grep provider
```

**Comment by dokterbob** [comment]
Here is where provider entries seem to be written to the datastore: https://github.com/libp2p/go-libp2p-kad-dht/blob/master/providers/providers_manager.go#L245

Based on that, a hook could be made for the datastore based on this: github.com/alanshaw/ipfs-hookds

However, this seems to provide a hook into the *datastore*, which should only give us *new* entries. Rather, we might want to know stuff about existing entries, i.e. availability. In which case, perhaps, we should be running a hydra.

Which could then yield a stream of providers, i.e. to a file or FIFO, from which the sniffer could read.

**Comment by dokterbob** [comment]
Having read the handlers code, it does seem that *currently*, the path is as follows:

1. `dht.handlerForMsgType` with `pb.Message_ADD_PROVIDER`
3. `dht.handleAddProvider`
4. `dht.ProviderManager.AddProvider`
5. `providers_manager.writeProviderEntry`
6. `dstore.Put`

As, technically, we have everything we need at level 1, and IPFS' API has been known to be hugely unstable (so far!), it might be best to implement an alternative `dht.dhtHandler` in a fork of `go-libp2p-kad-dht`, with which we can build a fork of IPFS.

It's a bit of a pain, but we might have less maintenance to do that in the alternative scenario. Regardless, the log tailing method above is preferable *if* we can get it to work.

**Comment by dokterbob** [comment]
We're currently working on using a fork of the hydra-booster - a many-headed DHT-only node - to feed in provider records from All The Network.

https://github.com/ipfs-search/hydra-booster/tree/provider_stream
