### ISSUE TITLE
Storing time series on availability

### ISSUE THREAD

**Issue by daviddias** [ipfs-search/ipfs-search#130]
Hi IPFS Search folks! I'm very interested to learn what is the average lifetime of a file on the IPFS network, from the moment it starts being provider to the moment that there are no more replicates (in the case of people stop serving it) and what is the average availability by day, month and year.

We are planning to build some scripts using the Hydra Booster for this, but I figured that probably you already have this information ready? If not, let me know if you would be interested in exploring this :) Thanks in advance!

**Comment by josselinchevalay** [comment]
hello, 

me too i'm very intrested about this question. 

Regards

**Comment by dokterbob** [comment]
We currently are not storing the info but would like to, it would be a great additive to our configuration.

We're using Elasticsearch as our backend, and expect to amend it with Redis in the near future. The biggest blocking factor is a data model that allows for efficient access of this information, providing historic availability data.

Should you wish to support us in this, it'd be much appreciated.

We're currently working on a [fork of the hydra-booster](https://github.com/ipfs-search/hydra-booster) which will produce a stream of hashes and providers. 

One of our other bottlenecks is starting to be hosting costs. We're currently only able to index part of the network, to do all of it will probably cost around € 400 / month. We're very much open to collaborating in this and/or sharing costs.
