### ISSUE TITLE
Unable to join your matrix server

### ISSUE THREAD

**Issue by jeffkhull** [ipfs-search/ipfs-search#174]
Hi all,

Wanted to give you a heads up, I'm not able to join your matrix server using the link provided in your readme.... see screenshot.

![image](https://user-images.githubusercontent.com/17109209/110321357-9211b280-7fdf-11eb-8ca3-3e8e5c25f86e.png)

**Comment by dokterbob** [comment]
That's a big issue! Thanks for reporting it. It does seem that matrix.org deleted our channel's alias. I suppose, if you're on Matrix.org and we give you admin permissions, you may create it again. Would be a great help.

Looking forward to see you in #ipfs-search:chat.weho.st

**Comment by dokterbob** [comment]
I updated the README with the correct URL.
