### ISSUE TITLE
Link to the root CID of website

### ISSUE THREAD

**Issue by kotovalexarian** [ipfs-search/ipfs-search#178]
I have a website in IPFS. It's root directory has CID `QmUmRHCveEsHAXu1FqHPCvMADLsuxfzm2G5QM4UERViPWs`. When I visit the website it downloads `index.html`, `assets/stylesheets/site.css`, `assets/stylesheets/site.js`. Links are relative.

![crypto_libertarian_website](https://user-images.githubusercontent.com/44363825/112541934-cce45a80-8dd5-11eb-96ae-4550f8fa5a5f.jpg)

However, [ipfs-search.com](https://ipfs-search.com) indexes the `index.html` with CID `QmSAXMzTJzh71fzDSMTdN9Kk5VmPW9fbsNQ12fqeAK6VLr` itself so relative links to assets and other pages are broken.

![crypto_libertarian_website_broken](https://user-images.githubusercontent.com/44363825/112542146-087f2480-8dd6-11eb-8525-1ccba73f0296.jpg)

---

Is it possible to find root CID of website and give link to it from the search engine?

**Comment by dokterbob** [comment]
Yes, if we encounter the directory containing an item, we use this by default to link to it. It might be we have not (yet) seen the hash of the root of your website.

We're very eager to implement an add API some time soon, once we're done with our current migration, that is. ;)
