### ISSUE TITLE
Cannot download the Snapshots. Error: could not resolve name.  

### ISSUE THREAD

**Issue by askender** [ipfs-search/ipfs-search#183]
ipfs resolve -r /ipns/12D3KooWKDDboo2aQzFxpHB7BXUUXudMr81ccC4d28eQPAfrgWQi
Error: could not resolve name

Thanks.

**Comment by askender** [comment]
@dokterbob   Any hint? I wish to analyses the snapshots and host a ipfs-search too.   Thanks!

**Comment by dokterbob** [comment]
Hi,

That’s super! I’m sorry, there seems to be a problem with the snapshots, we recently migrated servers. I’ll have a lookt at it next week!

Mathijs

**Comment by dokterbob** [comment]
I'm sorry this is taking more time than it arguably should have. We recently migrated from a single to a multi-node deployment and, regarding the snapshots, there are still some loose ends which are taking longer than expected to resolve.

This is important to us so I will get back to you on this ASAP. It might take up to 2 weeks. If it is of urgent importance for you to have access to the data, I might even be able to give you read access on the web archive directly.

**Comment by askender** [comment]
Cool!   It is important to me and the dweb.    I can wait.  But if [read access on the web archive] is easy for you, I would love to got one.

**Comment by dokterbob** [comment]
Hi, sorry for the wait. We've been trying to use Fleek's brand new S3 API but ran into some issues.
For now, I've made our S3 snapshots at Wasabi public, so you should be able to load the data: https://ipfs-search-snapshots-v8.s3.eu-central-1.wasabisys.com/

I'll be *very* happy to know if you run into any issues and/or have PR's for our documentation on the topic.

**Comment by askender** [comment]
Sorry, I ran into issues.    I don't know how to use S3 snapshots at Wasabi public, and it is not listed in https://ipfs-search.readthedocs.io/en/latest/snapshots.html

By the way, Is it possible you export ipfs/ipns snapshot to a car file, by using `ipfs dag export Qmxxx >Qmxxx_snapshot.car` , and transport it via some service?

**Comment by askender** [comment]
@dokterbob   Could you take a look about this issue?

**Comment by askender** [comment]
@dokterbob   Besices, I think it will be better you share the metadata in a jsonl format(every line is a json).   That will be cool!

**Comment by dokterbob** [comment]
> Sorry, I ran into issues. I don't know how to use S3 snapshots at Wasabi public, and it is not listed in https://ipfs-search.readthedocs.io/en/latest/snapshots.html

It *should*(tm) work exactly as in this manual except you don't need IPFS running, you should just be able to use the Wasabi URL.

> By the way, Is it possible you export ipfs/ipns snapshot to a car file, by using `ipfs dag export Qmxxx >Qmxxx_snapshot.car` , and transport it via some service?
Most computer systems are not comfortable dealing with files this large (1TB). In addition, we do not currently have enough space on any single machine to store this single file.

**Comment by askender** [comment]
Thanks for your help.

1.  I still don't know what is the relation of `https://ipfs-search-snapshots-v8.s3.eu-central-1.wasabisys.com/` and the doc.  I must miss some background information.    But I think we could start from the point 2(below): 

2. I'm a NLP researcher.   What I need is a tsv file of `title\thash`,   I think this file should be much less than 1T,  If it is easy to export this file for you,  could you help me?   
- Extra tsv file which I think can be useful is `hash\tparnet_hash_seperated_by_comma`,  But it takes much times to export and share, you can ignore it.  

3. I'm a dweb developer and I'm focus on a dweb search engine now too.  I contact and talk with Protocol Lab sometimes. I really think `a more web-native export of the metadata` is important and a spec is needed, and a simple tsv is a good start point.   (wikipedia have many kinds of dump files such as xml/sql/tsv, which I think is good for research and dweb)

4. I believe we can cooperate in the future.    I can help store file for longer time by using filecoin (I will also pin files in ipfs too), and I will contact some authors to help us add extra metadata such as license to the IPFS files.

**Comment by dokterbob** [comment]
> 1.  I still don't know what is the relation of `https://ipfs-search-snapshots-v8.s3.eu-central-1.wasabisys.com/` and the doc.  Maybe I missed some important background information.    But I think we could start from the point 2(below): 

You should be able to skip other steps, start with 'Restore' and use the URL `https://ipfs-search-snapshots-v8.s3.eu-central-1.wasabisys.com/` as a replacement for `http://localhost:8080/ipns/12D3KooWKDDboo2aQzFxpHB7BXUUXudMr81ccC4d28eQPAfrgWQi/backup/`.

> 2. I'm a NLP researcher (I write paper sometimes).   What I need is a tsv file of `title\thash`  (the hash can be hash/xxx too, the Direct link is not needed),   I think this file should be enough for a paper and dapp, and much less than 1T,  If it is easy to export this file for you,  could you help me?     (I will share/open-source all of my analysis/code and other things) (If this file is still 1T, I think most of the file is from wikipedia, you can ignore them(only include the dir-hash) for the first version) 

This is not trivial to do but you are welcome to implement the code, for example as a Python or JS script, which I could run for you on our cluster, *once*. Note that you would have to run our crawler locally for a bit to create a database to develop your export script with. A good starting point might be https://github.com/elasticsearch-dump/elasticsearch-dump

In addition, if you use our data we would greatly appreciate a citation. :)

> 3. I'm a dweb developer and I'm focus on a dweb search engine now too.  I contact and talk with Protocol Lab sometimes. I really think `a more web-native export of the metadata` is important and a spec is needed, and a simple tsv is a good start point.   (wikipedia have many kinds of dump files such as xml/sql/tsv, which I think is good for research and dweb)

A tsv will not make sense, JSON is much more web-native and considering the amount of data and the fact that it's a standard within IPFS IPLD-CBOR is the format of our preference. Regarding the data structure, I would like to start with simply exporting the data as we have it, excluding the `last-seen` field which is mutable.

> 4. I believe we can cooperate in the future.    I can help store file for longer time by using filecoin (I will also pin files in ipfs too), and I will contact some authors to help us add extra metadata such as license to the IPFS files.

We will be distributing our dataset under the [Open Data Commons Open Database License](https://opendatacommons.org/licenses/odbl/), the license recently adopted by OpenStreetMaps. You are *very* welcome to pin the contents of the S3-bucket above. You *should* be able to list and download it with tools such as boto.

> 5. I'm collecting some ipfs metadata too. I can share them to you if you need.

What data? I'm very curious. :)

**Comment by askender** [comment]
Thanks!!!
1. I found I'm a elasticsearch newby.
```
➜  elasticsearch-5.6.16 curl -XPUT "localhost:9200/_snapshot/myrepo4" -H 'Content-Type: application/json' -d'
{
  "type": "url",
  "settings": {
    "url": "https://ipfs-search-snapshots-v8.s3.eu-central-1.wasabisys.com/"
  }
}'
{"acknowledged":true}%
 ➜  elasticsearch-5.6.16 curl -XGET 'localhost:9200/_snapshot/myrepo4/_all?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Can't get text on a FIELD_NAME at 1:297"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "Can't get text on a FIELD_NAME at 1:297"
  },
  "status" : 500
}
```
https://discuss.elastic.co/t/error-in-getting-all-the-snapshots-under-a-repository/266034

2. I will implement the export code when I finish 1.     For paper, there will be a citation.

3.  yes, tsv is not good spec.(I meation it because file is too large)  I mean we can reduce the core field in metadata: Many need title, hash.  jsonl is ok: {'title':'1','hash':ba}   IPLD-CBOR is cooler.   Besides, maybe knowledge graph fileformat nt is also good for large dump, such as https://zenodo.org/record/4662515#.YMtUrjYzZfI do.  I will finish this part if I finish 1

4. yes. a clear spec of human-readablle file format is nice.   S3-bucket is also ok for now.  For Licence, I mean the license of the content itself, not the snapshot.

5. I will share the data in near future.  It is some blogs and some blog platform which use ipfs already.

For 1, 
- my connection to s3 network is not very fast.  and Maybe I should reasearch boto download. I need something like:   xxx https://your-s3-repo -O  /data/es/snapshot_repo  so that I can restore snapshot to es use `fs`  
- reduce the fields of metadata is useful to share the datasets in platforms such as https://www.kaggle.com/datasets.

**Comment by dokterbob** [comment]
Hi @askender, you're right that there should be a better way to exchange document metdatadata.

The reason the index is so large is partly because we indeed index the full textual contents of every item. In addition, we're actually searching a large dataset and the index on a corpus tends to be much larger than the corpus itself.

Our live dataset is currently over 2TB and growing fast.

Once again, we are *very* happy to work on an easily exchangeable format for metadata, preferably over IPFS and preferably in IPLD DAG-CBOR format, ideally through a HAMT-sharded directory with an entry for every hash. This will allow others to download/pin the full set, it will allow incremental storage, as well as efficient storage *and* browser-accessibility of JSON-compatible data.

As for the license; I suppose the data is licensed however the data was licensed. This is one of the reasons why we're not serving extracted content over an API but only extracted metadata. I'm not a legal expert so don't pin me down on this one.

**Comment by dokterbob** [comment]
I might be able to provide you with direct access to the bucket, please send me an email and I'll provide them to you.

The data resides in the EU at Wasabi (not Amazon), so I can imagine it'll take a while to make it to wherever you are. If you have about 4 TB available (I think it's the current size of the repo) you should be able to download it all and load it into ES much faster.

Alternatively, you can also run the crawler with Docker, create a small index and write up a script to extract the data in a format which makes sense to you and I could see if I can find time to run it on our servers (might take 2-3 weeks) but love to help science. :)

**Comment by askender** [comment]
> I suppose the data is licensed however the data was licensed. This is one of the reasons why we're not serving extracted content over an API but only extracted metadata. I'm not a legal expert so don't pin me down on this one.

Thanks. I will go deeper on this part. Thanks.   (For other who may interested: if the search-engine don't pin the data, the content on ipfs may gone, the user experience may not be good.  For my search-engine, I will pin the CC content. and I will contact other authors without licenses  to talk about the license in personal.) 

> I might be able to provide you with direct access to the bucket, please send me an email and I'll provide them to you.
> The data resides in the EU at Wasabi (not Amazon), so I can imagine it'll take a while to make it to wherever you are. If you have about 4 TB available (I think it's the current size of the repo) you should be able to download it all and load it into ES much faster.
Sorry, I'm amazon s3 newby,  sorry I don't want to pay a vps for a bucket.

> Alternatively, you can also run the crawler with Docker, create a small index and write up a script to extract the data in a format which makes sense to you and I could see if I can find time to run it on our servers (might take 2-3 weeks) but love to help science. :)
Yes. I will run the crawler with Docker, and write the script. The fake code(I will write a real one if I got time) is:
```python3
for doc in bucket:  # will learn how to extract from es
    new_doc = {}
    new_doc['title'] = doc['title']
    new_doc['hash'] = doc['hash']
    print(json.dumps(new_doc))  # TODO:  IPLD DAG-CBOR format
```

> Once again, we are very happy to work on an easily exchangeable format for metadata, preferably over IPFS and preferably in IPLD DAG-CBOR format, ideally through a HAMT-sharded directory with an entry for every hash. This will allow others to download/pin the full set, it will allow incremental storage, as well as efficient storage and browser-accessibility of JSON-compatible data.

How about we write a spec and finish a demo exchange file of it? I think it is better than just finish the script export part.

Besides, some papers you may interested:
Bringing Decentralized Search to Decentralized Services:  https://www.cis.upenn.edu/~sga001/papers/desearch-osdi21.pdf  
IPFS and Friends: A Qualitative Comparison of Next Generation Peer-to-Peer Data Networks 
 https://arxiv.org/pdf/2102.12737.pdf 

Glad to talk with you.! You project is cool!
