### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by happysalada** [ipfs-search/ipfs-search#192]
Here is the full error in the logs
```
Done crawling 'ipfs://QmUapCEEzx1YiHPbvbUoqkW7yW5yP5iuWKcTYmepC2YZJV', result: unexpected response from backend: unexpected status 500 Internal Server Error
``` 

I don't know if that is part of the expected errors.
I thought I would report, just in case.
Feel free to close this if it is expected.

**Comment by dokterbob** [comment]
Hi! Thanks for the feedback! There is a lot of messy stuff on IPFS, so responses like this are common.

If you get this kinda error, there should also be some feedback from the backend, which I think is `tika-extractor`. That should tell you more about what's going wrong.
