### ISSUE TITLE
I'm using the IPFS search site and I put in the CID from a smart contract's baseURI but I get no results :(

### ISSUE THREAD

**Issue by petercottonmouth** [ipfs-search/ipfs-search#195]
Whenever I go to the individual .json files one-by-one it pulls up in my browser and I can read the metadata. I'm just trying to find a way to look at the entire directory at once. Many thanks

**Comment by dokterbob** [comment]
Hi @petercottonmouth,

Thanks for the feedback!
Could you please provide a concrete example for us to replicate? 

Preferably along the following shape:
1. What were you doing?
2. What was the expected result?
3. What happened instead?

Thanks!
