### ISSUE TITLE
Add file / Submit file for indexing?

### ISSUE THREAD

**Issue by slrslr** [ipfs-search/ipfs-search#198]
Hello,

the search engine site https://ipfs-search.com does not suggest how to add file to its index.

What is fastest way with high probability, without giving real person link and they download?

**Comment by dokterbob** [comment]
Hi @slrslr,

Thanks for the feedback.
This has been on our roadmap for quite a while now. See: https://github.com/ipfs-search/ipfs-search-api/issues/12
If you are able and willing to implement it, we're very happy to discuss implementation details and we could discuss a bounty/funding.

Closing this one as it's a duplicate.
