### ISSUE TITLE
Did you disable the download image functionality?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ipfs-search/ipfs-search#199]
Hello,

I'm MB. A very nice and polite guy.

I tested ipfs search regularly during the past years. Last time was recently. At that time I could download images easily no problem.

When I tested searching for images today, if I click the image it shows full view but there is no way to download the image anymore. Also cannot find metadata.

Did you intentionally disable metadata and image downloading functionalities?

**Comment by bitcoinmeetups** [comment]
There's no CID in the metadata any more. Intentional?

**Comment by dokterbob** [comment]
We did not intentionally disable anything. In fact, if you look at our frontend repo you should see a ticket for it. 

https://github.com/ipfs-search/dweb-search-frontend/issues/39

Cheers.
