### ISSUE TITLE
How can I search IPFS using the api based on both keyword and last seen at the same time?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ipfs-search/ipfs-search#203]
Hello,

I'm MB. A very nice and polite guy.

How can I search IPFS using the api (curl) based on both keyword and last seen at the same time?

For example:

I would like to search for the keyword "water" but it's important that I only get results last seen within 7 days.

I know how to search for either water OR last seven days but how do I search for both at the same time?

Tried this but it doesn't work.

curl https://api.ipfs-search.com/v1/searc
h?q=water%3A%3Elast-seen%3A%3Enow%wa
ter-1M&type=file&page=1

**Comment by dokterbob** [comment]
Great question. As per the [API docs](https://app.swaggerhub.com/apis-docs/ipfs-search/ipfs-search/1.0.2#/default/get_search), our queries take [ES query string query syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-dsl-query-string-query). In addition, the *default* is AND.

So this query gives you all water from the last week. Also works in the frontend, by the way. `last-seen:>now-1w water`

curl equivalent:
`
curl -X 'GET' \
  'https://api.ipfs-search.com/v1/search?q=last-seen%3A%3Enow-1w%20water&type=file&page=1' \
  -H 'accept: application/json'
`

**Comment by bitcoinmeetups** [comment]
Very nice. If I also would like to search for a specific filetype, how would the curl command look if I may ask?

-------- Original Message --------

**Comment by dokterbob** [comment]
Please see the example in the API called 'Exact match on content-type'.
