### ISSUE TITLE
Just sniff IPFS CID's

### ISSUE THREAD

**Issue by Barq17** [ipfs-search/ipfs-search#212]
I would like to get newly added CID's on IPFS.

Can I just sniff IPFS CID's with this tool?

**Comment by dokterbob** [comment]
Hi @Barq17, for that you can use our sniffer https://github.com/ipfs-search/ipfs-sniffer, which pretends to be a bunch of DHT nodes, deduplicates found CID's and then writes them out to a RabbitMQ server.
