### ISSUE TITLE
Feature Suggestion: Use bleve as Search Engine

### ISSUE THREAD

**Issue by joeblew99** [ipfs-search/ipfs-search#22]
Currently we have a reliance on Elastic Search server which uses Java.
There is an equivalent called "Bleve" that has similar functionality,

 -It has an Apache licence.
- Written in Go.
- Already provides allot of value add functionality.
- It also designed for being sharded onto many servers, and so can handle high throughput.

DGraph implemented Bleve into their stack in one week. So, its not that much work at all.

Urls:
http://www.blevesearch.com/

https://github.com/blevesearch/bleve

There are many golang projects using bleve, and so heaps of example out there.

**Comment by dokterbob** [comment]
Hey there, thanks for the suggestion.

Does Breve support scaling to large clusters as well? (Additive) index snapshots? Fault tolerance? Automatic field type detection?
