### ISSUE TITLE
Search connected to Block Chain

### ISSUE THREAD

**Issue by madorian** [ipfs-search/ipfs-search#23]
Can't we connect search to block chain, so that it costs money to search? Then money pays for nodes for the processing

**Comment by madorian** [comment]
wow, I searched for this on google and found this thread and I thought; what a genius, then I saw that I was the one that posted it;)

**Comment by RangerMauve** [comment]
If by "Block Chain" you mean storing the search indexes in an IPFS Dag, I think it's a good idea. However this will be annoying to update as things stand right now.

**Comment by dokterbob** [comment]
To be honest; I've got 99 problems but a decentralized search ain't one.

If you feel like implementing this; great! We hope to have the index publicly available as ES snapshots some time soon, so you're welcome to take that.

However, creating a decentralized search app is currently WAY beyond the scope of this effort, as cool as it would be.  But, once again, it would be perfectly soothed for a parallel effort, once some people are willing to dedicate sufficient time to it.

Search is complicated, man. ;)

**Comment by dokterbob** [comment]
P.S. I don't intend to kill this discussion, just don't think this is the place for it. But if I could somehow facilitate such a discussion elsewhere, I'd be happy to hear about your suggestions.

**Comment by RangerMauve** [comment]
@dokterbob Is there something we can track for when the index will become publicly available? Would it just be a method for replicating the Elasticsearch data?

**Comment by dokterbob** [comment]
Yes, join the riot channel. And yes, it'll be just a public backup, essentially. 

RangerMauve <notifications@github.com> schreef op 5 februari 2018 19:07:00 GMT+00:00:
>@dokterbob Is there something we can track for when the index will
>become publicly available? Would it just be a method for replicating
>the Elasticsearch data?

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
