### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search#4]
1. What's this project about
2. Directory layout
3. Where and how to contribute
4. ... (suggestions welcome)

**Comment by ryobg** [comment]
That's the contribution guidelines? I think it is common to have CONTRIBUTING in the root with such info. I'm not sure whether point 1 matters, as it is in the ABOUT or the README. What I can think of with regard to contribution is:
* General places to contribute to: images, web design, translation, news spreading and etc.
* For each them have a kind of guideline. What process to follow, any policies taken into account (like using blue or green, do not use properietary, use Google's guidelines for javascript coding, fork and merge requests and etc.)
* Maybe any minutee meetings or communication channels.

**Comment by dokterbob** [comment]
Part of this would be CONTRIBUTING.md but if prefer to write that one myself. Apart from this it would be a technical description of the service infrastructure, the API and the inner functionings of the code.

**Comment by joelamouche** [comment]
@dokterbob did you write a CONTRIBUTING.md ?

**Comment by dokterbob** [comment]
Did you check whether I did? ;)

I suggest you make one, put yourself (and myself) on it for writing it in the first place and fire a pull request! :)

**Comment by joelamouche** [comment]
Yes I did check and couldn't find it. I'm assuming that means no. I wasn't sure you wanted someone else to write it since you said you'd write it in this thread.

Here is an adaptation of a standard contribution guideline to start:
https://hackmd.io/ZkYY9hYTRVuezm0eh0zHtA

**Comment by dokterbob** [comment]
Ok, forget what I said some months ago (like I did). Having something is better than having nothing at all - so I would happily accept a standard guideline to start - we can refine it later!
