### ISSUE TITLE
API: Metadata backend

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search#59]
We have a LOT of metadata we're currently storing (some of which we're indexing).

It would be great to have this available through the API, possibly for use in the frontend as well.

**Comment by arni077** [comment]
does the crawler can crawl within the website specific text itself or just crawl metadata?

**Comment by dokterbob** [comment]
It uses Tika to do both. 

arni077 <notifications@github.com> schreef op 19 juli 2018 21:58:23 CEST:
>does the crawler can crawl within the website specific text itself or
>just crawl metadata?

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by arni077** [comment]
@dokterbob  wow,from my observation i saw that even google crawler only crawl metadata.

**Comment by dokterbob** [comment]
Now online! https://api.ipfs-search.com/#metadata

(Code should be merged soon...)
